spring.application.name=realestatecrm
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-billowing-waterfall-b4qy8q3e.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KR3sPmpEo7nY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.fail-on-empty-beans=false

app.cors.allowed-origin=http://localhost:5173